/*
 * Main.java
 *
 * Created on January 7, 2005, 12:53 AM
 */

/**
 *
 * @author  Illya Kysil
 */
public class Main extends javax.swing.JFrame {
  
  /** Creates new form Main */
  public Main() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jList1 = new javax.swing.JList();
    jButton3 = new javax.swing.JButton();
    jCheckBox1 = new javax.swing.JCheckBox();
    jRadioButton1 = new javax.swing.JRadioButton();

    getContentPane().setLayout(new java.awt.FlowLayout());

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        exitForm(evt);
      }
    });

    jButton1.setText("jButton1");
    getContentPane().add(jButton1);

    jButton2.setText("jButton2");
    getContentPane().add(jButton2);

    jList1.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "1", "2", "3" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    getContentPane().add(jList1);

    jButton3.setText("jButton3");
    getContentPane().add(jButton3);

    jCheckBox1.setText("jCheckBox1");
    getContentPane().add(jCheckBox1);

    jRadioButton1.setText("jRadioButton1");
    getContentPane().add(jRadioButton1);

    pack();
  }//GEN-END:initComponents
  
  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit(0);
  }//GEN-LAST:event_exitForm
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    new Main().show();
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JList jList1;
  private javax.swing.JRadioButton jRadioButton1;
  // End of variables declaration//GEN-END:variables
  
}
